# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Maratona SBC de Programação
email: lucas.n.ferreira@ufv.br
description: >- # this means to ignore newlines until "baseurl:"
 Seja muito bem-vindo ao site da regional Viçosa da Maratona SBC de Programação 2024, organizada pelo Departamento de Informática da Universidade Federal de Viçosa. Aqui você encontrará informações sobre a competição, a programação, as inscrições, a localização e muito mais.
baseurl: "/maratona-sbc-ufv" # the subpath of your site, e.g. /blog
url: "https://lucasnfe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: pt

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Viçosa
      # img: ''
      # url: ''
    breakpoint: md
    links:
      - name: Sobre
        relative_url: /about/
      - name: Programação
        relative_url: /program/
      - name: Inscrições
        relative_url: /registration/
      - name: Localização
        relative_url: /location/
      - name: Contato
        relative_url: /contact/        
      - name: Edições Anteriores
        menu:
          - name: 2023
            disabled: true

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    # links:
    #   - name: Program
    #     relative_url: /program/
    #   - name: How to get there
    #     relative_url: /location/
    #   - name: Tickets
    #     disabled: true
    #     absolute_url: ''

  # Information boxes
  # info_bars:
  #   - title: Welcome to the Conference Theme for Jekyll!
  #     color: primary
  #     main_only: true
  #     text: |
  #       The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

  #       ---

  #       See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #   - text: This is just some random content for demonstration purposes.
  #     color: warning
  #     pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Prova
        color: info
      - name: Logística
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: -20.763061, -42.866951
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 18


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 30 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true